name    'deric-torque'
version '0.2.1'
source 'https://github.com/deric/puppet-torque.git'
author 'Tomas Barton'
license 'Apache License, Version 2.0'
summary 'Module for managing Torque'
description 'Torque is an open-source version of PBS'
project_page 'https://github.com/deric/puppet-torque'

dependency 'puppetlabs/stdlib', '>= 2.0.0'
dependency 'puppetlabs/apt', '>= 1.0.0'
dependency 'puppetlabs/concat', '>=1.0.0'
