name    'puppet-torque'
version '0.1.0'
source 'https://github.com/deric/puppet-torque.git'
author 'deric'
license 'Apache License, Version 2.0'
summary 'Module for managing Torque'
description 'Torque is an open-source version of PBS'
project_page 'https://github.com/deric/puppet-torque'

dependency 'puppetlabs/stdlib', '>= 2.0.0'
